/*1035 Password 
To prepare for PAT, the judge sometimes has to generate random passwords for the users. 
The problem is that there are always some confusing passwords since it is hard to distinguish 1 (one) from l (L in lowercase), 
or 0 (zero) from O (o in uppercase). One solution is to replace 1 (one) by @, 0 (zero) by %, l by L, and O by o.
Now it is your job to write a program to check the accounts generated by the judge, 
and to help the judge modify the confusing passwords.
Input Specification:
Each input file contains one test case. Each case contains a positive integer N (¡Ü1000), followed by N lines of accounts.
Each account consists of a user name and a password, both are strings of no more than 10 characters with no space.
Output Specification:
For each test case, first print the number M of accounts that have been modified, 
then print in the following M lines the modified accounts info, that is, the user names 
and the corresponding modified passwords. The accounts must be printed in the same order as they are read in.
If no account is modified, print in one line There are N accounts and no account is modified where N is the total number of accounts. 
However, if N is one, you must print There is 1 account and no account is modified instead.
*/
#include<cstdio>
#include<cstring>

struct account {
	char name[15];
	char password[15];
}user, temp[1010];

int main() {
	int n, t, m=0, count=0;
	bool flag;
	scanf("%d", &n);
	t = n;
	while(t--) {
		flag = false;
		scanf("%s %s", user.name, user.password);
		int len = strlen(user.password);
		for(int i=0; i<len; i++) {
			if(user.password[i] == '1') {
				user.password[i] = '@';
				flag = true;
			} else if(user.password[i] == '0') {
				user.password[i] = '%';
				flag = true;
			} else if(user.password[i] == 'l') {
				user.password[i] = 'L';
				flag = true;
			} else if(user.password[i] == 'O') {
				user.password[i] = 'o';
				flag = true;
			}
		}
		if(flag) {
			temp[m++] = user;
			count++;
		}
	}
	if(!count) {
		if(n==1) {
			printf("There is %d account and no account is modified", n);
		} else {
			printf("There are %d accounts and no account is modified", n);
		}
	} else {
		printf("%d\n", count);
		for(int i=0; i<count; i++) {
			printf("%s %s\n", temp[i].name, temp[i].password);
		}
	}
	return 0;
}
